storage:
  files:
  - path: {{GetCSEHelpersScriptFilepath}}
    mode: 0644
    contents:
      remote:
        compression: gzip
      inline: !!binary |
        {{GetVariableProperty "cloudInitData" "provisionSource"}}
